DigitalSignature/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("signature.urls", namespace="signature")),
    path('accounts/', include('django.contrib.auth.urls'))
]

signature/urls.py
from django.urls import path
from . import views

app_name = "signature"

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('signature', views.signature, name='signature'),
    path('identify', views.identify, name='identify'),
]

signature/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, unique=True)
    aadhaar = models.CharField(max_length=14, unique=True)

    def __str__(self):
        return self.user.email


class Signature(models.Model):
    # user = models.OneToOneField(User, unique=False, on_delete=models.CASCADE)
    email = models.CharField(max_length=100, unique=False)
    addressedTo = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    hash = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.email

signature/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Signature


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True,)
    last_name = forms.CharField(max_length=30, required=True,)
    email = forms.EmailField(max_length=254, required=True,)
    phone = forms.CharField(max_length=10, required=True,)
    aadhaar = forms.CharField(max_length=14, required=True,)

    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'phone',
                  'aadhaar',
                  'password1',
                  'password2',)


class SignatureForm(forms.Form):
    subject = forms.CharField(max_length=100, required=True,)
    addressedTo = forms.CharField(max_length=100, required=True,)

    class Meta:
        model = Signature
        fields = ('Subject', 'AddressedTo')

    @staticmethod
    def save(details, hashText):
        s = Signature(email=details["email"],
                      addressedTo=details["addressedTo"],
                      subject=details["subject"],
                      hash=hashText)
        s.save()


class IdentifyForm(forms.Form):
    hash = forms.CharField(max_length=32, required=True,)

    class Meta:
        fields = ('Hash',)

signature/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from signature.forms import RegisterForm, SignatureForm, IdentifyForm
from backend import *


def index(request):
    form = IdentifyForm()
    context = {'form': form}
    return render(request, 'signature/index.html', context)


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            create_profile(form)
            user = authentication(form)
            login(request, user)
            return redirect('signature:index')
    else:
        form = RegisterForm()
    context = {'form': form}
    return render(request, 'registration/register.html', context)


def dashboard(request):
    userSignatures = get_user_signatures(request)
    context = {"userSignatures": userSignatures}
    return render(request, 'signature/dashboard.html', context)


def signature(request):
    context = dict()
    if request.method == "POST":
        form = SignatureForm(request.POST)
        if form.is_valid():
            details = get_details(request)
            hashText = get_hash_text(details)
            form.save(details, hashText)
            context = {'form': form, 'hashText': hashText}
    else:
        form = SignatureForm()
        context = {'form': form}
    return render(request, 'signature/signature.html', context)


def identify(request):
    context = dict()
    if request.method == "POST":
        identity = get_identity(request)
        context = {"identity": identity.items()}
    return render(request, 'signature/identify.html', context)

signature/templates/signature/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<table>
    <tr>
        <th>Hash</th>
        <th>Subject</th>
        <th>Addressed To</th>
        <th>Date</th>
    </tr>
    {% for us in userSignatures %}
    <tr>
        <td>{{ us.hash }}</td>
        <td>{{ us.subject }}</td>
        <td>{{ us.addressedTo }}</td>
        <td>{{ us.date }}</td>
    </tr>
    {% endfor %}
    {% endblock %}
</table>
</body>
</html>

signature/templates/signature/identify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<table>
    {% for key,value in identity %}
    <tr>
        <td>{{ key }}</td>
        <td>{{ value }}</td>
    </tr>
    {% endfor %}
    {% endblock %}
</table>
</body>
</html>

signature/templates/signature/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Index</h1>
{% if user.is_authenticated %}
<h2>{{ user.username }}</h2>
<h2><a href="{% url 'signature:dashboard' %}">Dashboard</a></h2>
<h2><a href="{% url 'signature:signature' %}">Signature</a></h2>
<h2><a href="{% url 'logout' %}?next={% url 'signature:index' %}">Logout</a></h2>
{% else %}
<h2><a href="{% url 'login' %}">Login</a></h2>
<h2><a href="{% url 'signature:register' %}">Register</a></h2>
{% endif %}

{% block content %}
<h2>Sign up</h2>
<form method="post" action="{% url 'signature:identify' %}">
    {% csrf_token %}
    {% for field in form %}
    Enter signature to identify<br>
    {{ field }}
    {% if field.help_text %}
    <small style="color: grey">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    {% endfor %}
    <button type="submit">Identify</button>
</form>
{% endblock %}

</body>
</html>

signature/templates/signature/signature.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<h2>Generate Signature</h2>
<form method="post" action="{% url 'signature:signature' %}">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Generate</button>
    <p>{{ hashText }}</p>
</form>
{% endblock %}
</body>
</html>